name: Push Azure Container Instance Group template to Azure

on:
  push:
    branches:
      - master
    paths:
      - "iac/*.yaml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #Checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      #Replace the secrets in the template
      #Not a good practice and full fledge IAC solutions as bicep and terraform should be used
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$SubnetId"
          replace: "${{secrets.SUBNETID}}"
          include: "**kafka.yaml"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$StorageAccountKey"
          replace: "${{secrets.STORAGEACCOUNTKEY}}"
          include: "**kafka.yaml"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$DnsSearchDomain"
          replace: "${{secrets.DNSSEARCHDOMAIN}}"
          include: "**kafka.yaml"

      #Connect to azure and set the local credentials in action context
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #Call the "iac" template with secrets set from Github Repo
      - name: "Create Azure Container Instance"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az container create --resource-group ${{ secrets.RESOURCEGROUP }} --file kafka.yaml
