name: Push Azure Container Instance Group template to Azure

on:
  pull_request:
    branches: [master]
    paths:
      - "iac/*.yaml"

  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}

    steps:
      #Checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      #Replace the secrets in the template
      #Not a good practice and full fledge IAC solutions as bicep and terraform should be used
      - name: replace secret subnetId
        uses: jwsi/secret-parser@v1
        with:
          filename: "iac/kafka.yaml"
          secret-name: SUBNETID
          secret-value: ${{secrets.SUBNETID}}

      - name: replace secret Storage Account Key
        uses: jwsi/secret-parser@v1
        with:
          filename: "iac/kafka.yaml"
          secret-name: STORAGEACCOUNTKEY
          secret-value: ${{secrets.STORAGEACCOUNTKEY}}

      - name: replace secret DNS Search Domain
        uses: jwsi/secret-parser@v1
        with:
          filename: "iac/kafka.yaml"
          secret-name: DNSSEARCHDOMAIN
          secret-value: ${{secrets.DNSSEARCHDOMAIN}}

      #Connect to azure and set the local credentials in action context
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #Call the "iac" template with secrets set from Github Repo
      - name: "Create Azure Container Instance"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az container create --resource-group ${{ secrets.RESOURCEGROUP }} --file iac/kafka.yaml
